version: '3.3'

services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./
    # command: >
    #   sh -c "
    #   poetry shell &&
    #   poetry run alembic upgrade head" &&
    #   poetry run python src/db/insert.py &&
    #   cd ../../ &&
    #   poetry run uvicorn src.__main__:app --host 0.0.0.0 --port 8080
    #   "
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env


volumes:
  pg_volume: