version: '3.3'

services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  pg_volume: