"""Add feedback

Revision ID: 059906ad6b3b
Revises: e752762b9502
Create Date: 2024-09-13 17:16:02.859301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059906ad6b3b'
down_revision: Union[str, None] = 'e752762b9502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('creator_username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], name='feedback_bid_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
