"""empty message

Revision ID: e752762b9502
Revises: 4b1e38e0b792
Create Date: 2024-09-13 03:11:12.864015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e752762b9502'
down_revision: Union[str, None] = '4b1e38e0b792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('Construction', 'Delivery', 'Manufacture', name='tender_service_type'), nullable=False),
    sa.Column('status', sa.Enum('Created', 'Published', 'Closed', name='tender_status'), nullable=False),
    sa.Column('creator_username', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='tender_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tender_pkey')
    )
    op.create_table('bid',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Created', 'Published', 'Canceled', 'Approved', 'Rejected', name='bid_status'), nullable=False),
    sa.Column('creator_username', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tender_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='bid_organization_id_fkey'),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], name='bid_tender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bid_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('bid')
    op.drop_table('tender')
    op.execute('DROP TYPE IF EXISTS tender_status')
    op.execute('DROP TYPE IF EXISTS tender_service_type')
    op.execute('DROP TYPE IF EXISTS bid_status')
    op.execute('DROP TYPE IF EXISTS bid_decision')
    op.execute('DROP TYPE IF EXISTS bid_author_type')
