"""Add bid_desicion

Revision ID: e913a1eee022
Revises: 059906ad6b3b
Create Date: 2024-09-13 18:35:51.133527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e913a1eee022'
down_revision: Union[str, None] = '059906ad6b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE bid_decision AS ENUM ('Approved','Rejected');")
    op.add_column('bid', sa.Column('decision', sa.Enum('Approved', 'Rejected', name='bid_decision'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'decision')
    op.execute('DROP TYPE IF EXISTS bid_decision')
    # ### end Alembic commands ###
